In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
dados = pd.read_csv("cirrhosis.csv")
dados

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0      1     400      D  D-penicillamine  21464   F       Y            Y   
1      2    4500      C  D-penicillamine  20617   F       N            Y   
2      3    1012      D  D-penicillamine  25594   M       N            N   
3      4    1925      D  D-penicillamine  19994   F       N            Y   
4      5    1504     CL          Placebo  13918   F       N            Y   
..   ...     ...    ...              ...    ...  ..     ...          ...   
413  414     681      D              NaN  24472   F     NaN          NaN   
414  415    1103      C              NaN  14245   F     NaN          NaN   
415  416    1055      C              NaN  20819   F     NaN          NaN   
416  417     691      C              NaN  21185   F     NaN          NaN   
417  418     976      C              NaN  19358   F     NaN          NaN   

    Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0         Y     Y       14.5        261.0     2.60   156.0    1718.0  137.95   
1         Y     N        1.1        302.0     4.14    54.0    7394.8  113.52   
2         N     S        1.4        176.0     3.48   210.0     516.0   96.10   
3         Y     S        1.8        244.0     2.54    64.0    6121.8   60.63   
4         Y     N        3.4        279.0     3.53   143.0     671.0  113.15   
..      ...   ...        ...          ...      ...     ...       ...     ...   
413     NaN     N        1.2          NaN     2.96     NaN       NaN     NaN   
414     NaN     N        0.9          NaN     3.83     NaN       NaN     NaN   
415     NaN     N        1.6          NaN     3.42     NaN       NaN     NaN   
416     NaN     N        0.8          NaN     3.75     NaN       NaN     NaN   
417     NaN     N        0.7          NaN     3.29     NaN       NaN     NaN   

     Tryglicerides  Platelets  Prothrombin  Stage  
0            172.0      190.0         12.2    4.0  
1             88.0      221.0         10.6    3.0  
2             55.0      151.0         12.0    4.0  
3             92.0      183.0         10.3    4.0  
4             72.0      136.0         10.9    3.0  
..             ...        ...          ...    ...  
413            NaN      174.0         10.9    3.0  
414            NaN      180.0         11.2    4.0  
415            NaN      143.0          9.9    3.0  
416            NaN      269.0         10.4    3.0  
417            NaN      350.0         10.6    4.0  

[418 rows x 20 columns]

In [3]:
dados.isna().sum()

ID                 0
N_Days             0
Status             0
Drug             106
Age                0
Sex                0
Ascites          106
Hepatomegaly     106
Spiders          106
Edema              0
Bilirubin          0
Cholesterol      134
Albumin            0
Copper           108
Alk_Phos         106
SGOT             106
Tryglicerides    136
Platelets         11
Prothrombin        2
Stage              6
dtype: int64

In [4]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

dados_train_encoder = encoder.fit_transform(dados)

In [5]:
dados_train_encoder = pd.DataFrame(dados_train_encoder,columns=dados.columns)

In [6]:
corr = dados_train_encoder.corr()
corr["Status"].sort_values(ascending=False)


Status           1.000000
Bilirubin        0.488432
Copper           0.448492
Prothrombin      0.393819
Hepatomegaly     0.334591
SGOT             0.330179
Stage            0.320291
Ascites          0.317345
Edema            0.303299
Alk_Phos         0.270303
Spiders          0.231614
Tryglicerides    0.201293
Cholesterol      0.184023
Age              0.183308
Sex              0.118189
Drug            -0.025234
Platelets       -0.105007
Albumin         -0.255270
ID              -0.282416
N_Days          -0.439399
Name: Status, dtype: float64

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
impute = SimpleImputer(strategy="most_frequent")

In [9]:
impute.fit(dados)
dados_notNA = impute.transform(dados)

In [10]:
dados_notNA = pd.DataFrame(dados_notNA,columns=dados.columns)

In [11]:

from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index, test_index in split.split(dados_notNA,dados["Status"]):
    dados_train = dados_notNA.loc[train_index]
    dados_test = dados_notNA.loc[test_index]


In [12]:
dados_train

ID N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
83    84   4032      C          Placebo  20392   F       N            N   
269  270   1568      C  D-penicillamine   9598   F       N            Y   
295  296   1321      C          Placebo  11462   F       N            N   
69    70   3458      C  D-penicillamine  20600   F       N            N   
62    63    859      D          Placebo  17031   F       N            N   
..   ...    ...    ...              ...    ...  ..     ...          ...   
317  318   1680      C  D-penicillamine  15706   F       N            Y   
193  194   2449      C  D-penicillamine  16216   F       N            N   
145  146   2615      C          Placebo  12369   F       N            N   
275  276   1481      C  D-penicillamine  18302   F       N            N   
82    83   4050      C  D-penicillamine  20459   F       N            Y   

    Spiders Edema Bilirubin Cholesterol Albumin Copper Alk_Phos    SGOT  \
83        N     N       0.4       263.0    3.76   29.0   1345.0  137.95   
269       Y     N       1.0       448.0    3.74  102.0   1128.0    71.0   
295       N     N       0.8       328.0    3.31   62.0   1105.0   137.0   
69        N     N       0.6       260.0    4.64   20.0    666.0   54.25   
62        Y     Y      22.5       932.0    3.12   95.0   5396.0   244.9   
..      ...   ...       ...         ...     ...    ...      ...     ...   
317       N     N       0.7       260.0    3.68   52.0    559.0    71.3   
193       N     N       1.5       293.0     4.3   50.0    975.0  125.55   
145       N     S       1.2       260.0    3.89   58.0   1284.0   173.6   
275       N     N       1.0       219.0    3.85   67.0    640.0   145.0   
82        N     S       1.3       250.0     3.5   48.0   1138.0    71.3   

    Tryglicerides Platelets Prothrombin Stage  
83           74.0     181.0        11.2   3.0  
269         117.0     228.0        10.2   3.0  
295          95.0     293.0        10.9   4.0  
69          118.0     265.0        10.6   2.0  
62          133.0     165.0        11.6   3.0  
..            ...       ...         ...   ...  
317         118.0     306.0         9.5   2.0  
193          56.0     336.0         9.1   2.0  
145         118.0     239.0         9.4   3.0  
275         108.0      95.0        10.7   2.0  
82          100.0      81.0        12.9   4.0  

[334 rows x 20 columns]

In [13]:
x_train = dados_train.drop("Status",axis=1)
y_train = dados_train["Status"].copy()

In [14]:
x_train

ID N_Days             Drug    Age Sex Ascites Hepatomegaly Spiders  \
83    84   4032          Placebo  20392   F       N            N       N   
269  270   1568  D-penicillamine   9598   F       N            Y       Y   
295  296   1321          Placebo  11462   F       N            N       N   
69    70   3458  D-penicillamine  20600   F       N            N       N   
62    63    859          Placebo  17031   F       N            N       Y   
..   ...    ...              ...    ...  ..     ...          ...     ...   
317  318   1680  D-penicillamine  15706   F       N            Y       N   
193  194   2449  D-penicillamine  16216   F       N            N       N   
145  146   2615          Placebo  12369   F       N            N       N   
275  276   1481  D-penicillamine  18302   F       N            N       N   
82    83   4050  D-penicillamine  20459   F       N            Y       N   

    Edema Bilirubin Cholesterol Albumin Copper Alk_Phos    SGOT Tryglicerides  \
83      N       0.4       263.0    3.76   29.0   1345.0  137.95          74.0   
269     N       1.0       448.0    3.74  102.0   1128.0    71.0         117.0   
295     N       0.8       328.0    3.31   62.0   1105.0   137.0          95.0   
69      N       0.6       260.0    4.64   20.0    666.0   54.25         118.0   
62      Y      22.5       932.0    3.12   95.0   5396.0   244.9         133.0   
..    ...       ...         ...     ...    ...      ...     ...           ...   
317     N       0.7       260.0    3.68   52.0    559.0    71.3         118.0   
193     N       1.5       293.0     4.3   50.0    975.0  125.55          56.0   
145     S       1.2       260.0    3.89   58.0   1284.0   173.6         118.0   
275     N       1.0       219.0    3.85   67.0    640.0   145.0         108.0   
82      S       1.3       250.0     3.5   48.0   1138.0    71.3         100.0   

    Platelets Prothrombin Stage  
83      181.0        11.2   3.0  
269     228.0        10.2   3.0  
295     293.0        10.9   4.0  
69      265.0        10.6   2.0  
62      165.0        11.6   3.0  
..        ...         ...   ...  
317     306.0         9.5   2.0  
193     336.0         9.1   2.0  
145     239.0         9.4   3.0  
275      95.0        10.7   2.0  
82       81.0        12.9   4.0  

[334 rows x 19 columns]

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
dados_num = x_train.drop(["Sex", "Ascites", "Hepatomegaly", "Spiders","Edema","Drug"],axis=1)
dados_cat = ["Sex", "Ascites", "Hepatomegaly", "Spiders","Edema"]
from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
    ("num",StandardScaler(),list(dados_num)),
    ("cat",OrdinalEncoder(),dados_cat)
])

In [16]:
x_train_prepared = full_pipeline.fit_transform(x_train)
x_train_prepared

array([[-0.98386261,  1.85383244,  0.51427911, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.5593753 , -0.33140974, -2.35267588, ...,  1.        ,
         1.        ,  0.        ],
       [ 0.77509673, -0.55046608, -1.85758564, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.46944997,  0.59714081, -1.61668067, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.60915717, -0.40856723, -0.04083817, ...,  0.        ,
         0.        ,  0.        ],
       [-0.99215959,  1.86979606,  0.53207474, ...,  1.        ,
         0.        ,  1.        ]])

In [17]:
from sklearn.svm import SVC

svc = SVC()

svc.fit(x_train_prepared,y_train)


SVC()

In [18]:
from sklearn.model_selection import cross_val_score,cross_val_predict

score = cross_val_score(svc,x_train_prepared,y_train,cv=3,scoring="accuracy")


In [19]:
score

array([0.83928571, 0.7027027 , 0.76576577])

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
params = {
    "max_depth" :[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
    "max_features" :[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
    "n_estimators": [50,100,200,300,400,500],
    "max_leaf_nodes": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "max_samples": [25,50,75,100,125,150]
}

forest_classifier = RandomForestClassifier(random_state = 42)
forest_classifier.fit(x_train_prepared,y_train)
final_model = RandomizedSearchCV(forest_classifier,params,cv=3,scoring="accuracy")


In [21]:
final_model.fit(x_train_prepared,y_train)
final = final_model.best_estimator_
cross_val_score(final,x_train_prepared,y_train,cv = 3,scoring="accuracy")

c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
3 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\sklearn\base.py", line 638, in _validate_params
    v

array([0.86607143, 0.74774775, 0.74774775])

In [22]:
x_test = dados_test.drop("Status",axis=1)
y_test = dados_test["Status"].copy()
x_test_prepared = full_pipeline.fit_transform(x_test)

In [23]:
y_test_predict = forest_classifier.predict(x_test_prepared)
from sklearn.svm import SVC
svc = SVC(probability=True)
from sklearn.ensemble import VotingClassifier

voting = VotingClassifier(estimators = [("svc",svc),("random",forest_classifier)],voting = "soft")

In [24]:
from sklearn.metrics import precision_score,recall_score,roc_auc_score
cross_val_score(voting,x_test_prepared,y_test,cv=3,scoring="accuracy").mean()

0.7738095238095237

In [25]:
from sklearn.ensemble import BaggingClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
bagging = AdaBoostClassifier()

In [26]:
bagging.fit(x_train_prepared,y_train)

AdaBoostClassifier()

In [27]:
from sklearn.metrics import accuracy_score
y_test_predict = forest_classifier.predict(x_test_prepared)

print(f"{accuracy_score(y_test_predict,y_test) * 100:.2f}%")

83.33%


In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
cfx = confusion_matrix(y_true=y_test,y_pred=y_test_predict)
cfx

array([[44,  0,  3],
       [ 3,  0,  2],
       [ 6,  0, 26]], dtype=int64)

In [32]:
import tensorflow as tf
from tensorflow import keras

In [33]:
model = keras.models.Sequential()

In [46]:
model.add(keras.layers.Dense(50,activation="relu"))

In [47]:
model.add(keras.layers.Dense(30,activation="relu"))

In [48]:
model.add(keras.layers.Dense(3,activation="softmax"))

In [49]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="sgd",metrics=["accuracy"])

In [50]:
model.fit(x_train_prepared,y_train,epochs=30,validation_split=0.1)

Epoch 1/30


ValueError: in user code:

    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\engine\training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\engine\training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\engine\training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\engine\training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\daniel.suassuna\machine_learning\env\lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 19), found shape=(None, 18)
